"""Four-way penicillin ablation using 400 discretized-NLP KKT labels.

Unlike ``run_penicillin_ablation.py``, this program does not reconstruct
multipliers.  Its labels are generated by
``generate_penicillin_kkt_data.py``: a high-fidelity reduced direct
transcription is solved, and the active-set KKT equations are polished with
exact derivatives.  The multipliers therefore belong to that discretized NLP.
They are not asserted to be dual variables of the continuous-time problem.
"""
from __future__ import annotations

import argparse
import copy
import csv
import json
import os
import pickle
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from dataclasses import asdict, replace
from pathlib import Path

import numpy as np

os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# Reuse the already validated policy, process model, HDS evaluation, and
# normalized KKT-training implementation.  This keeps the only experimental
# difference between this and the legacy branch to the source of the duals.
from run_penicillin_ablation import (  # noqa: E402
    Config,
    DT,
    N,
    UMAX,
    g,
    gdot,
    lhs,
    ode,
    predict,
    summary,
    terminal_product,
    train,
)
from offline_safe_control.hds_lambda_corrector import HDSLambdaConfig, HDSLambdaCorrector  # noqa: E402
from offline_safe_control.adaptive_kkt_gate import AdaptiveKKTThresholds, audit_raw_hds_peaks  # noqa: E402

_EVALUATION_CORRECTOR: HDSLambdaCorrector | None = None


def _evaluation_worker_init(grid_size: int) -> None:
    """Build one HDS corrector per worker rather than per test sample."""
    global _EVALUATION_CORRECTOR
    _EVALUATION_CORRECTOR = HDSLambdaCorrector(
        ode, g, gdot, (0.0, UMAX),
        HDSLambdaConfig(grid_size=grid_size, max_step_fraction=100.0),
    )


def _evaluate_one(task: tuple[str, int, float, np.ndarray, bool, float]) -> dict:
    if _EVALUATION_CORRECTOR is None:
        raise RuntimeError("HDS evaluator worker was not initialized")
    name, index, x2, nominal, correct, inference_seconds = task
    initial = np.array([1.0, x2, 0.001, 250.0])
    raw_peak = _EVALUATION_CORRECTOR.audit(initial, nominal, DT)
    raw_product = terminal_product(x2, nominal, _EVALUATION_CORRECTOR)
    if not correct:
        return {
            "method": name, "sample_index": index, "x2_0": x2,
            "raw_hds_max_g": raw_peak, "applied_hds_max_g": raw_peak,
            "accepted": True, "fallback": False, "raw_product": raw_product,
            "applied_product": raw_product, "product_change": 0.0,
            "corrected_segments": 0, "mean_abs_lambda_minus_one": 0.0,
            "inference_seconds": inference_seconds, "filter_seconds": 0.0,
        }
    start = time.perf_counter()
    certificate = _EVALUATION_CORRECTOR.correct(initial, nominal, DT)
    filter_seconds = time.perf_counter() - start
    if not certificate.accepted:
        return {
            "method": name, "sample_index": index, "x2_0": x2,
            "raw_hds_max_g": raw_peak, "applied_hds_max_g": np.nan,
            "accepted": False, "fallback": True, "raw_product": raw_product,
            "applied_product": np.nan, "product_change": np.nan,
            "corrected_segments": sum(segment.corrected for segment in certificate.segments),
            "mean_abs_lambda_minus_one": np.nan, "inference_seconds": inference_seconds,
            "filter_seconds": filter_seconds,
        }
    applied = certificate.controls
    applied_peak = _EVALUATION_CORRECTOR.audit(initial, applied, DT)
    applied_product = terminal_product(x2, applied, _EVALUATION_CORRECTOR)
    lambdas = np.asarray([segment.lambda_value for segment in certificate.segments], dtype=float)
    return {
        "method": name, "sample_index": index, "x2_0": x2,
        "raw_hds_max_g": raw_peak, "applied_hds_max_g": applied_peak,
        "accepted": True, "fallback": False, "raw_product": raw_product,
        "applied_product": applied_product, "product_change": applied_product - raw_product,
        "corrected_segments": sum(segment.corrected for segment in certificate.segments),
        "mean_abs_lambda_minus_one": float(np.mean(np.abs(lambdas - 1.0))),
        "inference_seconds": inference_seconds, "filter_seconds": filter_seconds,
    }


def evaluate_methods_parallel(
    methods: list[tuple[str, np.ndarray, bool, float]], test_x2: np.ndarray, grid_size: int, workers: int,
) -> list[dict]:
    tasks = [
        (name, index, float(x2), np.asarray(controls[index], dtype=float), correct, inference_seconds)
        for name, controls, correct, inference_seconds in methods
        for index, x2 in enumerate(test_x2)
    ]
    if workers == 1:
        _evaluation_worker_init(grid_size)
        return [_evaluate_one(task) for task in tasks]
    with ProcessPoolExecutor(max_workers=workers, initializer=_evaluation_worker_init, initargs=(grid_size,)) as pool:
        return list(pool.map(_evaluate_one, tasks, chunksize=1))


def load_true_kkt_data(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict]:
    with path.open("rb") as handle:
        data = pickle.load(handle)
    required = {"initial_state", "optimal_controls", "objective", "path_duals", "hds_max_g", "kkt_certificate_accepted"}
    missing = required.difference(data)
    if missing:
        raise ValueError(f"Missing required true-KKT fields: {sorted(missing)}")
    x2 = np.asarray(data["initial_state"], dtype=np.float32)[:, 1]
    controls = np.asarray(data["optimal_controls"], dtype=np.float32)
    objective = np.asarray(data["objective"], dtype=np.float32)
    duals = np.asarray(data["path_duals"], dtype=np.float32)
    if x2.shape != (len(x2),) or controls.shape != (len(x2), N):
        raise ValueError(f"Unexpected state/control shapes: {x2.shape}, {controls.shape}")
    if objective.shape != (len(x2),) or duals.shape[0] != len(x2):
        raise ValueError("Objective or dual-label batch dimension is inconsistent")
    if not np.all(np.asarray(data["kkt_certificate_accepted"], dtype=bool)):
        raise ValueError("The input contains labels without an accepted KKT certificate")
    if np.max(np.asarray(data["hds_max_g"], dtype=float)) > 1e-7:
        raise ValueError("The input contains an HDS-infeasible teacher label")
    return x2, controls, objective, duals, data


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=ROOT / "kkt_collocation" / "data" / "penicillin_kkt_400_true_duals.pkl")
    parser.add_argument("--output", type=Path, default=ROOT / "kkt_collocation" / "results" / "penicillin_true_kkt_400_ablation")
    parser.add_argument("--epochs", type=int, default=200)
    parser.add_argument("--training-seed", type=int, default=20260715,
                        help="Random seed for network initialization/training; validation and test sets stay fixed.")
    parser.add_argument("--kkt-epochs", type=int, default=20)
    parser.add_argument("--kkt-weight", type=float, default=0.01)
    parser.add_argument("--constraint-penalty-weight", type=float, default=1.0)
    parser.add_argument("--test-samples", type=int, default=400)
    parser.add_argument("--validation-samples", type=int, default=100)
    parser.add_argument("--validation-seed", type=int,
                        help="Independent validation LHS seed. Defaults to the historical config seed + 1.")
    parser.add_argument("--test-seed", type=int,
                        help="Independent final-test LHS seed. Defaults to the historical config seed + 2.")
    parser.add_argument("--grid-size", type=int, default=31)
    parser.add_argument("--workers", type=int, default=4, help="Parallel HDS evaluation workers; use 1 for debugging.")
    parser.add_argument("--gate-rate", type=float, default=0.05)
    parser.add_argument("--gate-rate-normalized-violation", type=float, default=0.025)
    parser.add_argument("--gate-normalized-peak", type=float, default=0.03)
    parser.add_argument("--gate-engineering-scale", type=float, default=0.5)
    parser.add_argument("--gate-numerical-tolerance", type=float, default=1e-8)
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()

    cfg = Config(
        epochs=5 if args.smoke else args.epochs,
        kkt_epochs=2 if args.smoke else args.kkt_epochs,
        kkt_weight=args.kkt_weight,
        substeps=80,
        test_samples=12 if args.smoke else args.test_samples,
        validation_samples=8 if args.smoke else args.validation_samples,
        grid_size=args.grid_size,
        rollout_weight=0.0,
        seed=args.training_seed,
    )
    x2, controls, objective, duals, label_data = load_true_kkt_data(args.data)
    expected_nodes = N * cfg.substeps + 1
    if duals.shape != (len(x2), expected_nodes):
        raise ValueError(f"Dual shape {duals.shape} does not match {expected_nodes} rollout nodes")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    args.output.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(args.output / "teacher_labels.npz", x2=x2, controls=controls, objective=objective, path_duals=duals)

    print(f"Training S on {len(x2)} high-fidelity labels; device={device}.")
    supervised, mean_s, std_s = train(x2, controls, objective, duals, False, cfg, device)
    normalized = torch.tensor(((x2 - mean_s) / std_s)[:, None], dtype=torch.float32, device=device)
    with torch.no_grad():
        _, anchor_controls = supervised(normalized)

    print("Fine-tuning S+true-KKT from the supervised policy.")
    kkt_policy, mean_k, std_k = train(
        x2, controls, objective, duals, True, cfg, device,
        model=copy.deepcopy(supervised), epochs=cfg.kkt_epochs,
        learning_rate=cfg.kkt_learning_rate, anchor_controls=anchor_controls.cpu().numpy(),
    )
    penalty_policy, mean_p, std_p = train(
        x2, controls, objective, duals, False, cfg, device,
        model=copy.deepcopy(supervised), epochs=cfg.kkt_epochs,
        learning_rate=cfg.kkt_learning_rate, anchor_controls=anchor_controls.cpu().numpy(),
        path_penalty_weight=args.constraint_penalty_weight,
        constraint_scale=args.gate_engineering_scale,
    )

    validation_seed = cfg.seed + 1 if args.validation_seed is None else args.validation_seed
    test_seed = cfg.seed + 2 if args.test_seed is None else args.test_seed
    validation = lhs(cfg.validation_samples, validation_seed)
    test = lhs(cfg.test_samples, test_seed)
    np.save(args.output / "validation_x2.npy", validation)
    np.save(args.output / "test_x2.npy", test)
    u_s, infer_s = predict(supervised, mean_s, std_s, test, device)
    u_k, infer_k = predict(kkt_policy, mean_k, std_k, test, device)
    u_p, infer_p = predict(penalty_policy, mean_p, std_p, test, device)
    u_s_validation, _ = predict(supervised, mean_s, std_s, validation, device)
    thresholds = AdaptiveKKTThresholds(
        numerical_violation_tolerance=args.gate_numerical_tolerance,
        allowed_violation_rate=args.gate_rate,
        rate_normalized_violation=args.gate_rate_normalized_violation,
        allowed_normalized_peak_violation=args.gate_normalized_peak,
        engineering_constraint_scale=args.gate_engineering_scale,
    )
    validation_rows = evaluate_methods_parallel(
        [("raw-supervised-validation", u_s_validation, False, 0.0)], validation, cfg.grid_size, args.workers,
    )
    gate = audit_raw_hds_peaks([row["raw_hds_max_g"] for row in validation_rows], thresholds)
    adaptive_controls, adaptive_inference = (u_k, infer_k) if gate.kkt_refinement_required else (u_s, infer_s)
    adaptive_branch = "S+true-KKT" if gate.kkt_refinement_required else "S"
    rows = evaluate_methods_parallel(
        [("Never-KKT: S", u_s, False, infer_s),
         ("Constraint-penalty: S+P", u_p, False, infer_p),
         ("Always-KKT: S+true-KKT", u_k, False, infer_k),
         ("Never-KKT + HDS-lambda", u_s, True, infer_s),
         ("Constraint-penalty: S+P + HDS-lambda", u_p, True, infer_p),
         ("Always-KKT + HDS-lambda", u_k, True, infer_k)],
        test, cfg.grid_size, args.workers,
    )
    adaptive_raw_source = "Always-KKT: S+true-KKT" if gate.kkt_refinement_required else "Never-KKT: S"
    adaptive_safe_source = "Always-KKT + HDS-lambda" if gate.kkt_refinement_required else "Never-KKT + HDS-lambda"
    for source, target in ((adaptive_raw_source, f"Adaptive ({adaptive_branch})"),
                           (adaptive_safe_source, f"Adaptive ({adaptive_branch}) + HDS-lambda")):
        rows.extend([{**row, "method": target} for row in rows if row["method"] == source])
    with (args.output / "per_sample.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    report = {
        "config": asdict(cfg),
        "label_source": str(args.data),
        "data_split": {
            "validation_design": "independent Latin-hypercube sample in the declared initial-state domain",
            "validation_seed": validation_seed,
            "test_design": "independent Latin-hypercube sample in the declared initial-state domain",
            "test_seed": test_seed,
        },
        "kkt_note": "Path multipliers are active-set KKT-root numerical duals of an 801-node direct-transcription NLP; they are not continuous-time dual variables.",
        "constraint_penalty": {
            "weight": args.constraint_penalty_weight,
            "normalization_scale": args.gate_engineering_scale,
            "finetune_epochs": cfg.kkt_epochs,
            "learning_rate": cfg.kkt_learning_rate,
        },
        "adaptive_gate": {
            "thresholds": asdict(thresholds),
            "supervised_raw_validation": asdict(gate),
            "selected_branch": adaptive_branch,
        },
        "teacher_checks": {
            "samples": int(len(x2)),
            "max_hds_g": float(np.max(label_data["hds_max_g"])),
            "max_kkt_residual": float(np.max(label_data["optimality"])),
            "max_stationarity_residual": float(np.max(label_data["stationarity_norm"])),
        },
        "methods": summary(rows),
    }
    with (args.output / "summary.json").open("w", encoding="utf-8") as handle:
        json.dump(report, handle, ensure_ascii=False, indent=2)
    torch.save(
        {
            "S": supervised.state_dict(),
            "Penalty": penalty_policy.state_dict(),
            "true_KKT": kkt_policy.state_dict(),
            "normalization": {"S": [mean_s, std_s], "Penalty": [mean_p, std_p], "true_KKT": [mean_k, std_k]},
            "config": asdict(cfg),
            "label_source": str(args.data),
        },
        args.output / "models.pth",
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
