"""Train a KKT-regularized VDP policy from direct-transcription labels.

The input data must be generated by ``generate_vdp_kkt_data.py``.  In addition
to supervised control/objective labels, it contains path-constraint multipliers
from the same direct-transcription NLP.  The training loss combines supervised
learning, rollout consistency, and a reduced-space augmented-Lagrangian KKT
residual.  HDS is intentionally not differentiated through; it remains the
continuous-time evaluator used after training.
"""

from __future__ import annotations

import argparse
import json
import pickle
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import torch
from torch import nn

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from offline_safe_control.kkt_regularization import augmented_lagrangian_kkt_residual


@dataclass(frozen=True)
class TrainConfig:
    horizon: float = 5.0
    zoh_steps: int = 10
    substeps_per_zoh: int = 10
    y1_min: float = -0.4
    u_min: float = -0.3
    u_max: float = 1.0
    hidden_dim: int = 256
    epochs: int = 500
    learning_rate: float = 1e-3
    supervision_weight: float = 1.0
    rollout_weight: float = 0.5
    kkt_weight: float = 1e-3
    augmented_penalty: float = 10.0
    seed: int = 42

    @property
    def dt(self) -> float:
        return self.horizon / (self.zoh_steps * self.substeps_per_zoh)


class KKTPolicyValueNetwork(nn.Module):
    """Policy-value map with physical ZOH control bounds built into its output."""

    def __init__(self, config: TrainConfig) -> None:
        super().__init__()
        self.config = config
        self.backbone = nn.Sequential(
            nn.Linear(2, config.hidden_dim), nn.ReLU(),
            nn.Linear(config.hidden_dim, config.hidden_dim), nn.ReLU(),
            nn.Linear(config.hidden_dim, config.hidden_dim), nn.ReLU(),
        )
        self.value_head = nn.Linear(config.hidden_dim, 1)
        self.control_head = nn.Linear(config.hidden_dim, config.zoh_steps)

    def forward(self, normalized_initial_state: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        feature = self.backbone(normalized_initial_state)
        objective_normalized = self.value_head(feature)
        midpoint = (self.config.u_min + self.config.u_max) / 2.0
        half_range = (self.config.u_max - self.config.u_min) / 2.0
        controls = midpoint + half_range * torch.tanh(self.control_head(feature))
        return objective_normalized, controls


def differentiable_rollout(
    initial_state: torch.Tensor, controls: torch.Tensor, config: TrainConfig
) -> tuple[torch.Tensor, torch.Tensor]:
    """Return terminal cost and path values g=y1_min-y1 at all rollout nodes."""
    state = initial_state
    path_values = [config.y1_min - state[:, 0]]

    def dynamics(x: torch.Tensor, u: torch.Tensor) -> torch.Tensor:
        y1, y2, _ = x.unbind(dim=1)
        return torch.stack(
            ((1.0 - y2.square()) * y1 - y2 + u, y1, y1.square() + y2.square() + u.square()),
            dim=1,
        )

    for substep in range(config.zoh_steps * config.substeps_per_zoh):
        u = controls[:, substep // config.substeps_per_zoh]
        k1 = dynamics(state, u)
        k2 = dynamics(state + 0.5 * config.dt * k1, u)
        k3 = dynamics(state + 0.5 * config.dt * k2, u)
        k4 = dynamics(state + config.dt * k3, u)
        state = state + config.dt * (k1 + 2.0 * k2 + 2.0 * k3 + k4) / 6.0
        path_values.append(config.y1_min - state[:, 0])
    return state[:, 2], torch.stack(path_values, dim=1)


def load_dataset(path: Path, device: torch.device):
    with path.open("rb") as handle:
        data = pickle.load(handle)
    initial = torch.tensor(data["initial_state"], dtype=torch.float32, device=device)
    controls = torch.tensor(data["optimal_controls"], dtype=torch.float32, device=device)
    objective = torch.tensor(data["objective"], dtype=torch.float32, device=device).unsqueeze(1)
    multipliers = torch.tensor(data["path_duals"], dtype=torch.float32, device=device)
    if initial.ndim != 2 or initial.shape[1] != 3 or controls.shape[1] != 10:
        raise ValueError("unexpected VDP KKT data dimensions")
    if multipliers.shape[1] != 101:
        raise ValueError("trainer expects labels generated with 10 substeps per ZOH")
    return initial, controls, objective, multipliers


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("kkt_collocation/output/vdp_kkt_policy.pth"))
    parser.add_argument("--epochs", type=int, default=None)
    args = parser.parse_args()
    config = TrainConfig(epochs=args.epochs or TrainConfig.epochs)
    torch.manual_seed(config.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    initial, controls_ref, objective_ref, multipliers_ref = load_dataset(args.data, device)

    input_mean, input_std = initial[:, :2].mean(dim=0), initial[:, :2].std(dim=0).clamp_min(1e-8)
    objective_mean, objective_std = objective_ref.mean(), objective_ref.std().clamp_min(1e-8)
    x = (initial[:, :2] - input_mean) / input_std
    objective_ref_normalized = (objective_ref - objective_mean) / objective_std

    model = KKTPolicyValueNetwork(config).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=config.learning_rate)
    history: list[dict[str, float]] = []
    for epoch in range(1, config.epochs + 1):
        objective_normalized, controls = model(x)
        rollout_objective, path_values = differentiable_rollout(initial, controls, config)
        supervised = nn.functional.mse_loss(controls, controls_ref)
        supervised = supervised + 0.1 * nn.functional.mse_loss(objective_normalized, objective_ref_normalized)
        rollout_consistency = nn.functional.mse_loss(
            objective_normalized * objective_std + objective_mean,
            rollout_objective.unsqueeze(1),
        )
        kkt = augmented_lagrangian_kkt_residual(
            rollout_objective, controls, path_values, multipliers_ref, config.augmented_penalty
        )
        loss = config.supervision_weight * supervised
        loss = loss + config.rollout_weight * rollout_consistency + config.kkt_weight * kkt.total
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        if epoch == 1 or epoch % 25 == 0 or epoch == config.epochs:
            row = {
                "epoch": float(epoch),
                "total": float(loss.detach()),
                "supervised": float(supervised.detach()),
                "rollout": float(rollout_consistency.detach()),
                "stationarity": float(kkt.stationarity.detach()),
                "primal": float(kkt.primal_feasibility.detach()),
                "complementarity": float(kkt.complementarity.detach()),
            }
            history.append(row)
            print(" ".join(f"{key}={value:.3e}" for key, value in row.items()))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "model": model.state_dict(),
            "config": asdict(config),
            "input_mean": input_mean.detach().cpu().numpy(),
            "input_std": input_std.detach().cpu().numpy(),
            "objective_mean": float(objective_mean),
            "objective_std": float(objective_std),
            "data_path": str(args.data),
            "history": history,
        },
        args.output,
    )
    with args.output.with_suffix(".json").open("w", encoding="utf-8") as handle:
        json.dump({"config": asdict(config), "history": history}, handle, indent=2)
    print(f"Saved KKT-regularized VDP policy to {args.output}")


if __name__ == "__main__":
    main()
